### PR TITLE
Add support for pypy3

### PR DESCRIPTION
**Pull request by peterbell10**
Some of pypy3's C-API doesn't cast its arguments to `PyObject*` so the implicit
conversion from `py_ref` is never triggered. So, I remove the implicit conversion
operator and manually call `py_ref::get()` as appropriate.

### CODE REVIEW

**Comment by peterbell10** [comment]
So the `__init__.py` file in the tests folder seems to break `pypy -m pytest` where it can't import `_uarray`. Removing the file fixes `pypy` but also breaks the `cibuildwheel` jobs.

I seem to be finding conflicting advice: some say you [should have the file](https://stackoverflow.com/a/18971504),others say [not to include it](https://stackoverflow.com/a/41752043).

**Comment by hameerabbasi** [comment]
How about moving the entire `tests` directory out?

**Comment by hameerabbasi** [comment]
@mattip Have you ever experienced this before?

**Comment by peterbell10** [comment]
I am wondering if the difference might be because I have to call pytest as a python module `pypy3 -m pytest [...]` instead of on its own `pytest [...]`. From the [pytest docs](http://doc.pytest.org/en/latest/usage.html):
>This is almost equivalent to invoking the command line script `pytest [...]` directly, except that calling via `python` will also add the current directory to `sys.path`.

Then you have an extra `uarray` in `sys.path` messing things up.

**Comment by hameerabbasi** [comment]
I’m happy to merge this in, but I’d prefer to wait for Matti and see if he has an answer.

**Comment by hameerabbasi** [comment]
Would the `pytest` script not be installed in the case of PyPy?

**Comment by peterbell10** [comment]
The script should be there but I'm concerned about competing `pytest` versions in the `PATH`. Though I guess it might work since it's a clean `conda` environment.

**Comment by peterbell10** [comment]
Okay, looks like the `conda` environment was enough to call it as just `pytest`. It still needed the working directory to be outside of the project though.

**Comment by mattip** [comment]
I didn't know you could do `conda install -y -n pypy3-env -c conda-forge pypy3.6=7.3.0`. Does it still leave a cpython executable around?

**Comment by hameerabbasi** [comment]
Not in the environment, it doesn't:

```
conda create -n pypy3-env -c conda-forge pypy3.6=7.3.0
conda activate pypy3-env
which python  # Gives system python
which python3 # Gives system python3
```

**Pull request merged**
