### PR TITLE
Logo

### LINKED ISSUE #131: Collaborate on development of uarray logo, integrate into uarray

### PR DESCRIPTION
**Pull request by hameerabbasi**
Closes #131

### CODE REVIEW

**Comment by hameerabbasi** [comment]
The pipelines failure is due to the PyTorch conda channel being down right now.

**Comment by hameerabbasi** [comment]
Or rather, some issues with conda...

**Comment by rgommers** [comment]
Looking at https://uarray.readthedocs.io/en/latest/, the big logo at the top of the page doesn't need to be there - it's already in the sidebar. remove?

**Comment by hameerabbasi** [comment]
@rgommers done in 168ee8a3981aa8513d2560c3a77da72ad8dc3535.

**Pull request merged**
